[package]
name = "tuna_base_tool"
version = "0.1.0"
edition = "2021"

[alias]
run-with-args = "run -- arg1 arg2 arg3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.12", features = ["derive"] }
